#!/bin/bash

# --------------------------------------------
# trap ctrl-c and call ctrl_c() ( useful for cleanup )
trap ctrl_c INT

ctrl_c() {
  echo "** Trapped CTRL-C ! **"
  # do some cleanup
  exit 0
}

# --------------------------------------------
# Character codes generated by the keypresses.
arrowup='\[A'
arrowdown='\[B'
arrowrt='\[C'
arrowleft='\[D'
insert='\[2'
delete='\[3'

# --------------------------------------------
# Grep matching return values
SUCCESS=0
OTHER=65

#--------------------------------------------
# Arrows matching check functions

checkUpArrowMatch(){
  output=$(echo -n "$key" | grep "$arrowup")
  success=$?
  if [ "$success" -eq $SUCCESS ]
  then
    upArrowPress
  fi
}

checkDownArrowMatch(){
  output=$(echo -n "$key" | grep "$arrowdown")
  success=$?
  if [ "$success" -eq $SUCCESS ]
  then
    downArrowPress
  fi
}

checkLeftArrowMatch(){
  output=$(echo -n "$key" | grep "$arrowleft")
  success=$?
  if [ "$success" -eq $SUCCESS ]
  then
    leftArrowPress
  fi
}

checkRightArrowMatch(){
  output=$(echo -n "$key" | grep "$arrowrt")
  success=$?
  if [ "$success" -eq $SUCCESS ]
  then
    rightArrowPress
  fi
}

#--------------------------------------------
# Functions bind to arrow keys

upArrowPress(){
  echo -e "\rupArrow pressed !" 
  #echo -en "\r"
}

downArrowPress(){
  echo -e "\rdownArrow pressed !" 
  #echo -en "\r"
}

leftArrowPress(){
  echo -e "\rleftArrow pressed !" 
  #echo -en "\r"
}

rightArrowPress(){
  echo -e "\rrightArrow pressed !" 
  #echo -en "\r"
}

#--------------------------------------------

#--------------------------------------------
# Arrows check
checkArrowsMatch(){
  checkUpArrowMatch
  checkDownArrowMatch
  checkLeftArrowMatch
  checkRightArrowMatch
}

#--------------------------------------------
# Infinite loop
while true
do
  read -n3 key # Read 3 characters.
  checkArrowsMatch # check if input matches an arrow key
done


# my way ;D -- DEBUG --
#checkUpArrowKey(){ 
  #local arrowKeyCheck=`local output=$(echo -en "lolololopopol" | grep "pip"); local success=$?; echo $success`; 
  #local arrowKeyCheck=`echo 0`;
#  output=$(echo -en "lolololopopol" | grep "pop")
  #local arrowKeyCheck="$success";
  #if [ "$arrowKeyCheck" -eq $SUCCESS ]
#  if [ "$success" -eq $SUCCESS ]
#  then
#    echo "upArrow pressed !"
#  fi
#}

# debug test
#checkUpArrowKey


